# https://taskfile.dev

version: '3'


tasks:

  build:
    cmds:
      - echo "=> Building Windows executable..."
      - go build -v -o bin/iris-windows-amd64.exe -ldflags="-s -w" 

      - echo "=> Building Linux executable..."
      - GOOS=linux GOARCH=amd64 go build -v -o bin/iris-linux-amd64 -ldflags="-s -w" 

      - echo "=> Building Mac executable..."
      - GOOS=darwin GOARCH=amd64 go build -v -o bin/iris-darwin-amd64 -ldflags="-s -w" 

      - echo "=> Executables built successfully!"

  run:
    cmds:
      - go run .
  
  test:
    cmds:
      - go test -v ./...