# https://taskfile.dev

version: '3'


tasks:

  build:
    cmds:
      - go build -v -o bin/iris-windows-amd64.exe -ldflags="-s -w" ./cmd/iris

  run:
    cmds:
      - go run ./cmd/iris
  
  up:
    cmds:
      - go run ./cmd/iris up

  test:
    cmds:
      - go test -v ./...