# https://taskfile.dev

version: '3'


tasks:

  build:
    cmds:
      - echo "=> Building Windows executable..."
      - go build -v -o bin/iris-windows-amd64.exe -ldflags="-s -w" ./cmd/iris

      - echo "=> Building Linux executable..."
      - GOOS=linux GOARCH=amd64 go build -v -o bin/iris-linux-amd64 -ldflags="-s -w" ./cmd/iris

      - echo "=> Executables built successfully!"

  run:
    cmds:
      - go run ./cmd/iris
  
  run-up:
    cmds:
      - go run ./cmd/iris up

  test:
    cmds:
      - go test -v ./...