# https://taskfile.dev

version: '3'


tasks:

  build:
    cmds:
      - ./scripts/build.sh

  run:
    cmds:
      - go run ./cmd/iris
  
  up:
    cmds:
      - go run ./cmd/iris up

  test:
    cmds:
      - go test -v ./...